# Site settings
title: "ETOOBUSY"
description: "🚀 minimal blogging for the impatient"
origin: https://codeberg.org/polettix/etoobusy
baseurl: ""
url: "https://etoobusy.polettix.it"
author: "polettix"
timezone: Europe/Rome

# Build settings
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
# was: disqus_shortname: ETOOBUSY
disqus_shortname:

markdown: kramdown
kramdown:
  parse_block_html: true

exclude: ["_site", "_codeberg", "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "Gemfile.lock", "PROCESS.md"]

destination: '_codeberg'
keep_files: ['.git', '.domains']
