#!/bin/sh

if [ "$(stty size)" != '25 80' ] ; then
   printf >&2 'terminal size differnt from 80x25, continue? (y|N) '
   read input
   case "$input" in
      (y|Y)
         : # do nothing
         ;;
      (*)
         printf >&2 'bailing out\n'
         exit 1
         ;;
   esac
fi

filename=''
if [ $# -eq 0 ] ; then
   filename="$(tempfile)"
   set -- "$filename"
fi

PS1='$ ' asciinema rec --overwrite -c /bin/sh -i 1 "$@"

[ -z "$filename" ] || printf >&2 'saved to %s\n' "$filename"
