#!/usr/bin/env perl
use strict;
use warnings;
use feature 'say';
use Mojo::DOM;
use Mojo::File;
use Mojo::UserAgent;
my $ua = Mojo::UserAgent->new;
for my $input (@ARGV) {
    my $dom = $input =~ m{\A https?:// }imxs
        ? $ua->get($input)->result->dom
        : Mojo::DOM->new(Mojo::File->new($input)->slurp);
    $dom->find('a[href],img[src]')->each(
        sub { say $_[0]->attr(lc($_[0]->tag) eq 'a' ? 'href' : 'src') }
    );
}
